[project]
name = "retail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "plotly>=6.5.2",
    "pyspark[pipelines]>=4.1.1",
    "python-dotenv>=1.2.1",
    "streamlit>=1.54.0",
]
